name: Deploy Vecinos API

on:
  push:
    branches: [ "main" ]
    paths:
      - 'AppVecinos.API/**'
    tags:
    - 'v*.*.*'
    
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract version from tag
      id: vars
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Build API image
      run: | 
        docker build --platform linux --tag aminespinoza/vecinosapi:latest -f src/Dockerfile .
    - name: Publish API image to Docker Hub
      run: |
        docker push aminespinoza/vecinosapi:latest
