name: Deploy Vecinos API

on:
  push:
    branches: [ "amin-patch1" ]
#    paths:
#      - 'AppVecinos.API/**'
    
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3  
          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build API image
      run: | 
        docker build --platform linux --tag aminespinoza/vecinosapi:latest -f AppVecinos.API/Dockerfile .
    - name: Publish API image to Docker Hub
      run: |
        docker push aminespinoza/vecinosapi:${{ env.VERSION }}
    - name: Confirm process is done
      run: |
        echo 'Process is done'
