name: Deploy Vecinos Web

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AppVecinos.Web/
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3  
          
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build WebApp image
      run: | 
        docker build --platform linux --tag marcelamq/vecinosweb:latest .
        
    - name: Publish WebApp image to Docker Hub
      run: |
        docker push marcelamq/vecinosweb
